### ISSUE TITLE
keep getting this error message

### ISSUE THREAD

**Issue by gonzalez78** [Seeed-Studio/Touch_Screen_Driver#1]
![screen shot 2014-08-12 at 6 38 03 pm](https://cloud.githubusercontent.com/assets/8433098/3900343/d84b210a-228a-11e4-9f29-28c4c5d35682.png)
I keep trying all the different suggestions but still i keep getting that same error message. How can i fix it? I have the Arduino Uno R3 and the Seeed studio Touch Screen 2.8" but it does not have the Memory Card slot so I'm guessing its the first version

**Comment by Erutan409** [comment]
@gonzalez78 I'm fairly confident you *probably* don't care, anymore; given that you submitted this year's ago...

I'd guess it's an issue with the Arduino IDE version and/or you may need to just redefine the `__PRESURE` macro in the top of that sketch.
